spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
